# Generated by Django 2.1.1 on 2018-09-10 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jedies', '0002_auto_20180910_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer',
            field=models.CharField(choices=[('Y', 'Да'), ('N', 'Нет')], max_length=3),
        ),
    ]
